// @moritakaaz/opencode-apc - Aggressive Auto Context Pruning plugin for opencode
// Wraps @tarquinen/opencode-dcp with pre-configured aggressive settings (15k trigger)
// Install: opencode plugin @moritakaaz/opencode-apc@latest --global

import type { Plugin } from "@opencode-ai/plugin";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { homedir } from "os";

// Current config version — bump when APC_CONFIG shape changes
const CONFIG_VERSION = 1;

/**
 * Aggressive pruning config for DCP.
 * Triggers compression at 15k tokens to maximize token savings.
 */
const APC_CONFIG = {
  $schema:
    "https://raw.githubusercontent.com/Opencode-DCP/opencode-dynamic-context-pruning/master/dcp.schema.json",
  _apcVersion: CONFIG_VERSION,
  compress: {
    mode: "range",
    permission: "allow",
    maxContextLimit: 15000,
    minContextLimit: 8000,
    nudgeFrequency: 3,
    nudgeForce: "strong",
  },
  manualMode: {
    enabled: false,
    automaticStrategies: true,
  },
  strategies: {
    deduplication: {
      enabled: true,
    },
    purgeErrors: {
      enabled: true,
      turns: 2,
    },
  },
};

const PREFIX = "[opencode-apc]";

function log(message: string): void {
  console.error(`${PREFIX} ${message}`);
}

function warn(message: string): void {
  console.error(`${PREFIX} WARN: ${message}`);
}

/**
 * Validates an existing config file for required fields.
 * Returns true if the config looks healthy, false if it may need attention.
 */
function validateExistingConfig(configPath: string): boolean {
  try {
    const raw = readFileSync(configPath, "utf-8");
    // Strip single-line comments for JSON parsing
    const stripped = raw.replace(/^\s*\/\/.*$/gm, "");
    const parsed = JSON.parse(stripped);

    // Check required top-level structure
    if (!parsed.compress || typeof parsed.compress !== "object") {
      warn(`Config at ${configPath} is missing "compress" section`);
      return false;
    }

    if (typeof parsed.compress.maxContextLimit !== "number") {
      warn(`Config at ${configPath} is missing "compress.maxContextLimit"`);
      return false;
    }

    return true;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    warn(`Config at ${configPath} could not be validated: ${msg}`);
    return false;
  }
}

/**
 * Generates the config file content string.
 */
function generateConfigContent(): string {
  return (
    "// Auto-generated by @moritakaaz/opencode-apc\n" +
    "// Aggressive context pruning: triggers at 15k tokens\n" +
    JSON.stringify(APC_CONFIG, null, 2) +
    "\n"
  );
}

/**
 * Ensures project-level .opencode/dcp.jsonc exists with aggressive defaults.
 * If a config already exists, it validates but never overwrites.
 */
function ensureApcConfig(projectDir: string): void {
  const opencodeDir = join(projectDir, ".opencode");
  const projectConfig = join(opencodeDir, "dcp.jsonc");
  const projectConfigJson = join(opencodeDir, "dcp.json");

  // Validate existing config if present
  if (existsSync(projectConfig)) {
    validateExistingConfig(projectConfig);
    return;
  }
  if (existsSync(projectConfigJson)) {
    validateExistingConfig(projectConfigJson);
    return;
  }

  try {
    if (!existsSync(opencodeDir)) {
      mkdirSync(opencodeDir, { recursive: true });
    }

    writeFileSync(projectConfig, generateConfigContent(), "utf-8");
    log(`Created project config: ${projectConfig}`);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    warn(`Failed to create project config at ${projectConfig}: ${msg}`);
  }
}

/**
 * Ensures global config exists so DCP works even without a project config.
 */
function ensureGlobalConfig(): void {
  const configDir = process.env.XDG_CONFIG_HOME
    ? join(process.env.XDG_CONFIG_HOME, "opencode")
    : join(homedir(), ".config", "opencode");

  const globalJsonc = join(configDir, "dcp.jsonc");
  const globalJson = join(configDir, "dcp.json");

  // Validate existing config if present
  if (existsSync(globalJsonc)) {
    validateExistingConfig(globalJsonc);
    return;
  }
  if (existsSync(globalJson)) {
    validateExistingConfig(globalJson);
    return;
  }

  try {
    if (!existsSync(configDir)) {
      mkdirSync(configDir, { recursive: true });
    }

    writeFileSync(globalJsonc, generateConfigContent(), "utf-8");
    log(`Created global config: ${globalJsonc}`);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    warn(`Failed to create global config at ${globalJsonc}: ${msg}`);
  }
}

const plugin: Plugin = async (ctx) => {
  // Ensure aggressive DCP config files exist
  try {
    ensureGlobalConfig();
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    warn(`Unexpected error in ensureGlobalConfig: ${msg}`);
  }

  if (ctx.directory) {
    try {
      ensureApcConfig(ctx.directory);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      warn(`Unexpected error in ensureApcConfig: ${msg}`);
    }
  }

  // Delegate to DCP plugin
  try {
    const dcp = await import("@tarquinen/opencode-dcp");
    const hooks = await dcp.default(ctx);
    return hooks;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    warn(`Failed to load @tarquinen/opencode-dcp: ${msg}`);
    // Return empty hooks so opencode doesn't crash
    return {};
  }
};

export default plugin;
