// @moritakaaz/opencode-apc - Aggressive Auto Context Pruning plugin for opencode
// Wraps @tarquinen/opencode-dcp with pre-configured aggressive settings (7k trigger)
// Install: opencode plugin @moritakaaz/opencode-apc@latest --global

import type { Plugin } from "@opencode-ai/plugin";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { homedir } from "os";

// Current config version — bump when APC_CONFIG shape changes
// When bumped, existing configs with a lower _apcVersion are auto-upgraded
const CONFIG_VERSION = 2;

/**
 * Aggressive pruning config for DCP.
 * Triggers compression at 7k tokens to maximize token savings.
 */
const APC_CONFIG = {
  $schema:
    "https://raw.githubusercontent.com/Opencode-DCP/opencode-dynamic-context-pruning/master/dcp.schema.json",
  _apcVersion: CONFIG_VERSION,
  compress: {
    mode: "range",
    permission: "allow",
    maxContextLimit: 7000,
    minContextLimit: 3500,
    nudgeFrequency: 3,
    nudgeForce: "strong",
  },
  manualMode: {
    enabled: false,
    automaticStrategies: true,
  },
  strategies: {
    deduplication: {
      enabled: true,
    },
    purgeErrors: {
      enabled: true,
      turns: 2,
    },
  },
};

const PREFIX = "[opencode-apc]";

function log(message: string): void {
  console.error(`${PREFIX} ${message}`);
}

function warn(message: string): void {
  console.error(`${PREFIX} WARN: ${message}`);
}

/**
 * Validates an existing config file for required fields.
 * Returns true if the config looks healthy, false if it may need attention.
 * Skips validation for schema-only configs (e.g. DCP-generated placeholders).
 */
function validateExistingConfig(configPath: string): boolean {
  try {
    const raw = readFileSync(configPath, "utf-8");
    // Strip single-line comments for JSON parsing
    const stripped = raw.replace(/^\s*\/\/.*$/gm, "");
    const parsed = JSON.parse(stripped);

    // Schema-only config (e.g. created by DCP itself) — nothing to validate
    const keys = Object.keys(parsed).filter((k) => k !== "$schema");
    if (keys.length === 0) {
      return true;
    }

    // Check required top-level structure
    if (!parsed.compress || typeof parsed.compress !== "object") {
      warn(`Config at ${configPath} is missing "compress" section`);
      return false;
    }

    if (typeof parsed.compress.maxContextLimit !== "number") {
      warn(`Config at ${configPath} is missing "compress.maxContextLimit"`);
      return false;
    }

    return true;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    warn(`Config at ${configPath} could not be validated: ${msg}`);
    return false;
  }
}

/**
 * Checks if an existing config should be upgraded based on _apcVersion.
 * Returns true if the config was generated by APC and has a lower version.
 * User-customized configs (no _apcVersion field) are never upgraded.
 */
function shouldUpgradeConfig(configPath: string): boolean {
  try {
    const raw = readFileSync(configPath, "utf-8");
    const stripped = raw.replace(/^\s*\/\/.*$/gm, "");
    const parsed = JSON.parse(stripped);

    // No _apcVersion means user created/customized this config — don't touch it
    if (typeof parsed._apcVersion !== "number") {
      return false;
    }

    // Upgrade if existing version is lower than current
    return parsed._apcVersion < CONFIG_VERSION;
  } catch {
    // Can't parse — don't risk overwriting
    return false;
  }
}

/**
 * Generates the config file content string.
 */
function generateConfigContent(): string {
  return (
    "// Auto-generated by @moritakaaz/opencode-apc\n" +
    "// Aggressive context pruning: triggers at 7k tokens\n" +
    JSON.stringify(APC_CONFIG, null, 2) +
    "\n"
  );
}

/**
 * Ensures project-level .opencode/dcp.jsonc exists with aggressive defaults.
 * If a config already exists with an older _apcVersion, it gets upgraded.
 * If a config exists without _apcVersion (user-customized), it's never overwritten.
 */
function ensureApcConfig(projectDir: string): void {
  const opencodeDir = join(projectDir, ".opencode");
  const projectConfig = join(opencodeDir, "dcp.jsonc");
  const projectConfigJson = join(opencodeDir, "dcp.json");

  // Check existing configs — upgrade if outdated, skip if user-customized
  if (existsSync(projectConfig)) {
    if (shouldUpgradeConfig(projectConfig)) {
      writeFileSync(projectConfig, generateConfigContent(), "utf-8");
      log(`Upgraded project config (v${CONFIG_VERSION}): ${projectConfig}`);
    } else {
      validateExistingConfig(projectConfig);
    }
    return;
  }
  if (existsSync(projectConfigJson)) {
    if (shouldUpgradeConfig(projectConfigJson)) {
      writeFileSync(projectConfigJson, generateConfigContent(), "utf-8");
      log(`Upgraded project config (v${CONFIG_VERSION}): ${projectConfigJson}`);
    } else {
      validateExistingConfig(projectConfigJson);
    }
    return;
  }

  try {
    if (!existsSync(opencodeDir)) {
      mkdirSync(opencodeDir, { recursive: true });
    }

    writeFileSync(projectConfig, generateConfigContent(), "utf-8");
    log(`Created project config: ${projectConfig}`);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    warn(`Failed to create project config at ${projectConfig}: ${msg}`);
  }
}

/**
 * Ensures global config exists so DCP works even without a project config.
 * Upgrades outdated APC-generated configs automatically.
 */
function ensureGlobalConfig(): void {
  const configDir = process.env.XDG_CONFIG_HOME
    ? join(process.env.XDG_CONFIG_HOME, "opencode")
    : join(homedir(), ".config", "opencode");

  const globalJsonc = join(configDir, "dcp.jsonc");
  const globalJson = join(configDir, "dcp.json");

  // Check existing configs — upgrade if outdated, skip if user-customized
  // Global config is not validated because DCP applies sensible defaults
  // when compress section is absent (schema-only configs are legitimate)
  if (existsSync(globalJsonc)) {
    if (shouldUpgradeConfig(globalJsonc)) {
      writeFileSync(globalJsonc, generateConfigContent(), "utf-8");
      log(`Upgraded global config (v${CONFIG_VERSION}): ${globalJsonc}`);
    }
    return;
  }
  if (existsSync(globalJson)) {
    if (shouldUpgradeConfig(globalJson)) {
      writeFileSync(globalJson, generateConfigContent(), "utf-8");
      log(`Upgraded global config (v${CONFIG_VERSION}): ${globalJson}`);
    }
    return;
  }

  try {
    if (!existsSync(configDir)) {
      mkdirSync(configDir, { recursive: true });
    }

    writeFileSync(globalJsonc, generateConfigContent(), "utf-8");
    log(`Created global config: ${globalJsonc}`);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    warn(`Failed to create global config at ${globalJsonc}: ${msg}`);
  }
}

const plugin: Plugin = async (ctx) => {
  // Ensure aggressive DCP config files exist
  try {
    ensureGlobalConfig();
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    warn(`Unexpected error in ensureGlobalConfig: ${msg}`);
  }

  if (ctx.directory) {
    try {
      ensureApcConfig(ctx.directory);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      warn(`Unexpected error in ensureApcConfig: ${msg}`);
    }
  }

  // Delegate to DCP plugin
  try {
    const dcp = await import("@tarquinen/opencode-dcp");
    const hooks = await dcp.default(ctx);
    return hooks;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    warn(`Failed to load @tarquinen/opencode-dcp: ${msg}`);
    // Return empty hooks so opencode doesn't crash
    return {};
  }
};

export default plugin;
