// @moritakaaz/opencode-apc - Aggressive Auto Context Pruning plugin for opencode
// Wraps @tarquinen/opencode-dcp with pre-configured aggressive settings (15k trigger)
// Install: opencode plugin @moritakaaz/opencode-apc@latest --global

import type { Plugin } from "@opencode-ai/plugin";
import { existsSync, mkdirSync, writeFileSync } from "fs";
import { join } from "path";
import { homedir } from "os";

/**
 * Aggressive pruning config for DCP.
 * Triggers compression at 15k tokens to maximize token savings.
 */
const APC_CONFIG = {
  $schema:
    "https://raw.githubusercontent.com/Opencode-DCP/opencode-dynamic-context-pruning/master/dcp.schema.json",
  compress: {
    mode: "range",
    permission: "allow",
    maxContextLimit: 15000,
    minContextLimit: 8000,
    nudgeFrequency: 3,
    nudgeForce: "strong",
  },
  manualMode: {
    enabled: false,
    automaticStrategies: true,
  },
  strategies: {
    deduplication: {
      enabled: true,
    },
    purgeErrors: {
      enabled: true,
      turns: 2,
    },
  },
};

/**
 * Ensures global dcp.jsonc exists with aggressive defaults.
 * If a global config already exists, it won't be overwritten
 * (user's existing preferences take priority via DCP's merge system).
 * Instead we ensure the project-level .opencode/dcp.jsonc is set.
 */
function ensureApcConfig(projectDir: string): void {
  // Ensure project-level .opencode/dcp.jsonc with aggressive settings
  const opencodeDir = join(projectDir, ".opencode");
  const projectConfig = join(opencodeDir, "dcp.jsonc");
  const projectConfigJson = join(opencodeDir, "dcp.json");

  // Don't overwrite if project config already exists
  if (existsSync(projectConfig) || existsSync(projectConfigJson)) {
    return;
  }

  // Create .opencode dir if needed
  if (!existsSync(opencodeDir)) {
    mkdirSync(opencodeDir, { recursive: true });
  }

  const content =
    "// Auto-generated by @moritakaaz/opencode-apc\n" +
    "// Aggressive context pruning: triggers at 15k tokens\n" +
    JSON.stringify(APC_CONFIG, null, 2) +
    "\n";

  writeFileSync(projectConfig, content, "utf-8");
}

/**
 * Ensures global config exists so DCP works even without a project config.
 */
function ensureGlobalConfig(): void {
  const configDir = process.env.XDG_CONFIG_HOME
    ? join(process.env.XDG_CONFIG_HOME, "opencode")
    : join(homedir(), ".config", "opencode");

  const globalJsonc = join(configDir, "dcp.jsonc");
  const globalJson = join(configDir, "dcp.json");

  // Don't overwrite existing global config
  if (existsSync(globalJsonc) || existsSync(globalJson)) {
    return;
  }

  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }

  const content =
    "// Auto-generated by @moritakaaz/opencode-apc\n" +
    "// Aggressive context pruning: triggers at 15k tokens\n" +
    JSON.stringify(APC_CONFIG, null, 2) +
    "\n";

  writeFileSync(globalJsonc, content, "utf-8");
}

const plugin: Plugin = async (ctx) => {
  // Ensure aggressive DCP config files exist
  ensureGlobalConfig();
  if (ctx.directory) {
    ensureApcConfig(ctx.directory);
  }

  // Delegate to DCP plugin
  const dcp = await import("@tarquinen/opencode-dcp");
  const hooks = await dcp.default(ctx);

  return hooks;
};

export default plugin;
